import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { WalletProfileContextProvider } from "@/components/contexts/wallet-context";
import { SolanaProvider } from "@/components/contexts/SolanaContext";
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import { HeroPattern } from "@/components/ui/HeroPattern";
import AppHeader from "@/components/app-header";
import Sidebar from "@/components/sidebar";
import { HeaderLayout } from "@/components/header-layout";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Bundler Space",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <WalletProfileContextProvider>
          <SolanaProvider>
            <AppHeader />
            <HeaderLayout>
              <HeroPattern />
              {children}
              <ToastContainer
                position="bottom-right"
                autoClose={5000}
                hideProgressBar={false}
                newestOnTop={false}
                closeOnClick
                rtl={false}
                pauseOnFocusLoss
                draggable
                pauseOnHover
                theme="dark"
              />
            </HeaderLayout>
          </SolanaProvider>
        </WalletProfileContextProvider>
      </body>
    </html>
  );
}