'use client'; // Add this directive to make it a Client Component

import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { WalletProfileContextProvider } from "@/components/SolanaWallet/wallet-context";
import { SolanaProvider } from "@/components/SolanaWallet/SolanaContext";
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
// Import Solana wallet adapter styles
import '@solana/wallet-adapter-react-ui/styles.css';
import { HeroPattern } from "@/components/ui/HeroPattern";
import AppHeader from "@/components/app-header";
import { HeaderLayout } from "@/components/header-layout";
import { usePathname } from "next/navigation"; // Changed from useRouter to usePathname

const poppins = Poppins({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
});

const metadata: Metadata = {
  title: "Bundler Space",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();

  return (
    <html lang="en" className="dark">
      <body className={`${poppins.className} antialiased`}>
        <WalletProfileContextProvider>
          <SolanaProvider>
            <div className="flex flex-col h-screen">
              {pathname === "/" && <AppHeader />}
              <HeaderLayout>
                {pathname !== "/" && <HeroPattern />}
                {children}
                <ToastContainer
                  position="bottom-right"
                  autoClose={5000}
                  hideProgressBar={false}
                  newestOnTop={false}
                  closeOnClick
                  rtl={false}
                  pauseOnFocusLoss
                  draggable
                  pauseOnHover
                  theme="dark"
                />
              </HeaderLayout>
            </div>
          </SolanaProvider>
        </WalletProfileContextProvider>
      </body>
    </html>
  );
}